### PR TITLE
Hkl import geo

### PR DESCRIPTION
**Pull request by ambarb**
changed `from hkl.diffract import E4CV` to `from hkl.geometries import E4CV` to address #2 

diffract would not work for me.  did not test on latest hklpy though.
https://github.com/bluesky/hklpy/releases/tag/v1.0.0

### CODE REVIEW

**Comment by ambarb** [comment]
@jklynch if you want me to strip out the order of input execution, is there a software based tool I can use to do that?

**Comment by jklynch** [comment]
@ambarb I just learned `nbconvert` can remove cell output (if that's what you had in mind):

    python3 -m nbconvert --clear-output bluesky_hkl.ipynb

There are other tools to do this but for a single notebook this is pretty good, plus `nbconvert` is installed in our conda environments.

**Comment by jklynch** [comment]
@maffettone has a [PR](https://github.com/NSLS-II/scientific-python-cookiecutter/pull/104) to the scientific python cookiecutter that configures another tool to automatically strip notebook outputs.

**Comment by prjemian** [comment]
With v1.0.0, try `from hkl import E4CV`

**Review by jklynch — CHANGES_REQUESTED** [review]
would you be willing to try stripping all the output with nbconvert?

**Comment by ambarb** [comment]
yes. will try to use package to strip out , but probably not tonight.

**Comment by ambarb** [comment]
that was stupid easy and you just gave me a copy paste task.  thanks @jklynch

**Review by jklynch — APPROVED** [review]

**Pull request merged**
